In [96]:
import pandas as pd
import numpy as np

import re

Energy = pd.read_excel("assets/Energy Indicators.xls", usecols='C:F', skiprows=17, skipfooter=38)

columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

Energy.columns = columns

for col in Energy.columns[1:]:
    Energy[col] = pd.to_numeric(Energy[col], errors='coerce')


Energy['Energy Supply'] = Energy['Energy Supply'].apply(lambda x: x * 10**6 if not pd.isna(x) else x)

Energy['Country'] = Energy['Country'].str.replace(r'\d+$| \(.*\)', '')

Energy['Country'].replace({"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}, inplace=True)

GDP = pd.read_csv('assets/world_bank.csv', skiprows=4)

GDP.replace({"Korea, Rep.": "South Korea",  "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"},inplace=True)

GDP.rename(columns={'Country Name' : 'Country'}, inplace=True)

ScimEn = pd.read_excel('assets/scimagojr-3.xlsx')

drop_cols = [str(i) for i in range(1960, 2006)]
for col in GDP.columns:
    if col in drop_cols:
        GDP.drop(col, inplace=True, axis=1)


gdp_col = ['Country','2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']

GDP = GDP[gdp_col]

mer1 = pd.merge(ScimEn, Energy, how='inner', on="Country")
res = pd.merge(mer1, GDP, how='inner', on="Country").set_index('Country')

res_15 = res[res['Rank'] <= 15]

res.head(n=20)

C:\Users\droni\AppData\Local\Temp\ipykernel_2664\1333696271.py:18: FutureWarning: The default value of regex will change from True to False in a future version.
  Energy['Country'] = Energy['Country'].str.replace(r'\d+$| \(.*\)', '')

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Turkey,17,5879,5827,91857,23165,15.62,104,4.897000e+09,64.0,28.536690,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
Norway,18,5675,5634,32693,6024,5.76,74,1.388000e+09,273.0,97.635580,4.190512e+11,4.313284e+11,4.329860e+11,4.259607e+11,4.285247e+11,4.326762e+11,4.445694e+11,4.490094e+11,4.589539e+11,4.662883e+11
Netherlands,19,5170,5105,48351,6067,9.35,85,3.199000e+09,190.0,6.324659,8.127830e+11,8.428435e+11,8.571640e+11,8.248696e+11,8.364397e+11,8.503550e+11,8.413664e+11,8.371985e+11,8.456636e+11,8.624973e+11
Sweden,20,4565,4494,57889,9632,12.68,95,2.044000e+09,212.0,46.598460,4.726099e+11,4.887020e+11,4.859797e+11,4.607834e+11,4.883793e+11,5.013917e+11,4.999562e+11,5.061616e+11,5.176362e+11,5.388264e+11
Malaysia,21,3914,3881,25545,6597,6.53,62,3.417000e+09,116.0,7.754589,2.163030e+11,2.299275e+11,2.410371e+11,2.373885e+11,2.550169e+11,2.685170e+11,2.832141e+11,2.965633e+11,3.143352e+11,3.299022e+11

In [98]:
sets_before = max([len(df) for df in (Energy, GDP, ScimEn)])

mer1 = pd.merge(ScimEn, Energy, how='inner', on="Country")
res = pd.merge(mer1, GDP, how='inner', on="Country").set_index('Country')

out1 = pd.merge(ScimEn,Energy,how="outer",left_on="Country",right_on="Country")
out2  =pd.merge(out1,GDP,how="outer",left_on="Country",right_on="Country")

res = len(out2) - len(res) 
res

158

In [73]:
gdp_col = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']

sel = res_15[gdp_col]

avgGDP = sel.mean(axis=1).sort_index(ascending=False)

avgGDP

# selected = res_15[gdp_col]

# avgGDP = selected.mean(axis=1)
# avgGDP
res_15

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [74]:
pos = avgGDP.index[5]

res = abs(sel.loc[pos][-1] - sel.loc[pos][0])

In [75]:
capita_mean = res_15['Energy Supply per Capita'].mean()
capita_mean

157.6

In [76]:
max_capita =(res_15['% Renewable'].max(), res_15['% Renewable'].idxmax())
max_capita

(69.64803, 'Brazil')

In [77]:
quont = res_15['Self-citations'] / res_15['Citations']
res = (quont.idxmax(),  quont.max())
res

('China', 0.6893126179389422)

In [78]:
res = res_15['Energy Supply'] / res_15['Energy Supply per Capita']
res.sort_values(ascending=False, inplace=True)
res.index[2]

'United States'

In [79]:
res_15.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

In [80]:
res_15['PopEst'] = res_15['Energy Supply'] / res_15['Energy Supply per Capita']
res_15['Citable documents per capita'] = res_15['Citable documents'] / res_15['PopEst']
res = res_15['Citable documents per capita'].corr(res_15['Energy Supply per Capita'],method='pearson',)

In [81]:
median = res_15['% Renewable'].sort_values().median()
res_15['% Renewable above or low'] = (res_15['% Renewable'] >= median).astype(int)
res_15['% Renewable above or low']

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: % Renewable above or low, dtype: int32

In [82]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'
                  }

res = res_15['PopEst'].groupby(by=ContinentDict).agg(['size', 'sum', 'mean', 'std'])


res.index.name = 'Continent'
res = res.reindex(['Asia', 'Australia', 'Europe', 'North America', 'South America'])

res.head()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

In [83]:
bins = pd.cut(res_15['% Renewable'], 5)

res = res_15.groupby([ContinentDict, bins]).size()
res = res[res != 0]
res

Country        % Renewable
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

In [84]:
PopEst = res_15['PopEst'].apply(lambda x: '{0:,}'.format(x))
PopEst

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object